### ISSUE TITLE
Finesse data update procedure

### ISSUE THREAD

**Issue by eroten** [Metropolitan-Council/covid-poops#13]
Work folks in ES to streamline regular data updates

**Comment by ashleyasmus** [comment]
new [branch](https://github.com/Metropolitan-Council/covid-poops/tree/raw-data-compile)

**Comment by ashleyasmus** [comment]
- [ ] @lfetch0025: Set up database connection to get daily wastewater flow rates. save script as .db file (will automatically git-ignore, thanks @eroten)
- [ ] @lfetch0025: Set up script to pull wastewater flow rate data. 
- [ ] @lfetch0025: QA/QC - compare wastewater flow rate data to that pulled by hand (excel connections) by Steve in [this excel sheet](https://github.com/Metropolitan-Council/covid-poops/blob/main/data/raw-load-data.xlsx)
- [ ] @ashleyasmus: delete .xlsx files from [branch](https://github.com/Metropolitan-Council/covid-poops/tree/raw-data-compile)
- [ ] @ashleyasmus: add connections to sharepoint for raw data
- [ ] @ashleyasmus: create sample date -- > sample id --> sample run date --> excel sheet data date crosswalk table
- [ ] @ashleyasmus  and @lfletch0025: find missing spreadsheets/sample data & find them from Steve
- [ ] @ashleyasmus and @lfletch0025: write metadata for raw data
- [ ] @ashleyasmus: QA/QC compiled raw data against [steve's raw load data](https://github.com/Metropolitan-Council/covid-poops/blob/main/data/raw-load-data.xlsx) and [steve's raw variant data](https://github.com/Metropolitan-Council/covid-poops/blob/main/data/raw-variant-data.xlsx)
- [ ] @eroten: review [code ](https://github.com/Metropolitan-Council/covid-poops/blob/raw-data-compile/R/d_parse_raw.R)for parsing raw data
