### ISSUE TITLE
add figure to app: load by variant

### ISSUE THREAD

**Issue by ashleyasmus** [Metropolitan-Council/covid-poops#43]
this will need to get approved by  steve & george before publishing to app, but basic idea is to:

- [x] place a radio button on the "variants" tab of the dashboard to select "variant proportions (%)" or "variant load (number of copies)"
- [x] when variant proportions is selected, the frequency plot is shown, when variant load is shown, the load x variant plot is shown
- [ ] Add contextual text from the Rmd document (in the load x variant section) to the app to describe the data

The code for the plotly() graph lives here, under loadxvariantplot: reports/wastewater-monitoring-report-developing-version

**Comment by eroten** [comment]
![image](https://user-images.githubusercontent.com/16826194/153066869-57c9a048-1cc6-47fd-b7c3-5e2db4ecea43.png)

**Comment by ashleyasmus** [comment]
closed with f155c92097156f28b8d2f0ec2e1fd8b5ed594514
