### ISSUE TITLE
Add contextual text to app to describe variant count data

### ISSUE THREAD

**Issue by ashleyasmus** [Metropolitan-Council/covid-poops#45]
When variant count data is selected, should print text that includes some or all of the following: 

#### Another way of looking at the variant data
The dominance of various SARS-CoV-2 variants has ebbed and flowed over time. The current dominant variant, Omicron, became dominant in late December. The total amount of SARS-CoV-2 virus in wastewater has also been higher during the Omicron wave relative to earlier periods of the COVID-19 Pandemic, consistent with higher case counts in the region.

###### How to read this graph:
This graph shows the measured number of copies per person per day of each variant in wastewater. Points are daily data; lines and shaded areas are averages of the previous 7 days. The gray area in the background is the 7-day average total viral load. Variant proportions do not always add to 100%, so slight discrepancies between the total viral load and that of the individual variants are expected.

**Comment by eroten** [comment]
Closed in #43
