### ISSUE TITLE
Use min of 0 for both y axes?

### ISSUE THREAD

**Issue by knumat** [Metropolitan-Council/covid-poops#53]
I'm looking at the "Tracking COVID-19 Prevalence with Metro Plant Wastewater" graph here:
https://metrotransitmn.shinyapps.io/metc-wastewater-covid-monitor/

Currently, the primary y-axis has a minimum of -70, while the secondary y-axis has a minimum of 0.  This is confusing to me, since these two values appear to be (approximately) proportionally related, so I would expect them to both have a minimum of 0.  In its current state, the wastewater data misleadingly appears to show a significant baseline amount of virus, even during periods with few detected cases (e.g. July 2021).

Here is what the current graph looks like:
<img width="851" alt="current_graph" src="https://user-images.githubusercontent.com/29646487/156029362-0d9ce761-933c-46da-9c56-ef2d7c18b734.png">

I think this version would be more accurate/helpful:
<img width="851" alt="proposed_graph" src="https://user-images.githubusercontent.com/29646487/156029393-f395d2d3-7e1a-4f5e-9132-2eb1f00b2cd4.png">

Note: I generated the second image by clicking on the "0" in the bottom-left corner of the graph and changing the minimum from -70 to 0.

**Comment by knumat** [comment]
In case it is helpful, I tried to look through the code to see how to make this change.  Based on the Plotly R documentation, it appears that you could switch set the "rangemode" to "nonnegative":
https://plotly.com/r/axes/#nonnegative-tozero-and-normal-rangemode

It appears that this graph is generated in this file:
https://github.com/Metropolitan-Council/covid-poops/blob/main/metc-wastewater-covid-monitor/server.R

I'm not positive, but I think you could add the rangemode parameter to the "ay" axis definition here:
https://github.com/Metropolitan-Council/covid-poops/blob/main/metc-wastewater-covid-monitor/server.R#L112

**Comment by eroten** [comment]
@knumat this is very helpful! Thank you. I'm working on a fix with `rangemode = "nonnegative"` now.
