### ISSUE TITLE
Question: What is the source data for clean_load_data.csv?

### ISSUE THREAD

**Issue by eggsurplus** [Metropolitan-Council/covid-poops#61]
For district-level decisions, looking to find the source for clean_load_data.csv so that we can monitor the copies_day_person_M_mn each day. 

Any help on where this is coming from would be greatly appreciated.

**Comment by ashleyasmus** [comment]
Hello! The canonical source of data are spreadsheets (.xlsx) that are e-mailed from the University of Minnesota lab to Council Staff.  These spreadsheets have undergone some manual cleaning by Wastewater lab staff before they end up in our hands.
Although samples are taken daily, they are only analyzed weekly. So, you're getting the most up-to-date data that we have :)

**Comment by eggsurplus** [comment]
Many thanks! This helps.
