### ISSUE TITLE
Interactive graph is too busy

### ISSUE THREAD

**Issue by Lex137** [Metropolitan-Council/covid-poops#65]
When I hover over your interactive graph of wastewater surveillance data (https://metrotransitmn.shinyapps.io/metc-wastewater-covid-monitor/), there is too much overlapping content to be able to reliably read any of the data. In some areas, the individual daily readings are too clustered together to see or hover over the 7-day trend and the background case data is completely invisible.

Possible fixes:
Provide controls (such as toggles or checkboxes) to turn certain graph elements (daily readings, trendline, case rate) on or off.
Provide a control for selecting a date range to zoom the graph to, so the individual reading data can be more spaced out and to allow room for reading the other data on the graph.

**Comment by eroten** [comment]
Hi @Lex137. Thanks for letting us know and providing fix ideas! 🚀  Could you provide a screenshot of what you are seeing, please? Also, are you on desktop or mobile?

The interactive plots are made with [plotly](https://plotly.com/graphing-libraries/). The functionalities you've mentioned are built in already.

- You can click on an item in the legend to toggle that element visibility in the plot, and double click to make it the only element visible. The legend is just below the x-axis in the variant plot. 
- To zoom in on a certain section of the plot, move your cursor over an empty section of the plot (not over a line or dot), then click and drag to make a box.  Release the click, and the plot will zoom into the selected area. 

You can find more detail on plotly navigation [here](https://plotly.com/chart-studio-help/zoom-pan-hover-controls/)

Plotly adds a small plotly-branded toolbar to the upper right corner by default.  We generally remove it to cut down on visual clutter. Do you think the toolbar would help?

**Comment by Lex137** [comment]
Ooh, thanks for clarifying. That helps. So maybe my suggestion would simplify to adding some brief instructions to that page.

Also, I'm not seeing a legend on that page (on desktop, Chrome) with items I could click on to toggle its visibility:

![wastewaterdata](https://user-images.githubusercontent.com/76714175/162335072-2b52fbfe-b8f9-42c6-9503-088d82cb1043.PNG)
.

**Comment by eroten** [comment]
Ah I see. I will see what we can do about adding a legend. I'm tagging @lfletch0025, as we are updating the data this morning. Could we integrate these changes into the update PR?

- [ ] Add instructions on plot interactivity 
- [ ] Add legend to prevalence (main) plot
