### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by riggs** [Metropolitan-Council/covid-poops#74]
Who can we lobby to get more frequent updates? I realize this is mostly a side/volunteer project, but it's also the best source of data for infection rates in the metro. I would like to lobby the appropriate elected officials to provide more resources for this project so it can be updated more frequently.

Thank you!

**Comment by eroten** [comment]
Hi @riggs, thanks for your interest in this project. If you could, please send the Metropolitan Council public information office an email [here](public.info@metc.state.mn.us).
